config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  root 'welcome#index'
  get '/about', to: 'about#show'

  get '/login', to: 'visitors/sessions#new'

  get '/search', to: 'search#index'
  get '/search/details', to: 'search#show'

  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#googleAuth'
  get '/auth/failure', to: redirect('/')

  get '/profile/questionaire', to: 'profiles#new'
  get '/profile/:id', to: 'profiles#show'
  get '/profile/:id/edit', to: 'profiles#edit'
  patch '/profile/:id', to: 'profiles#update'
  post '/profile', to: 'profiles#create'
  delete '/profile/:id', to: 'profiles#destroy'

  get '/plants', to: 'plants#index'

	namespace :user do
		get '/mygardens', to: 'mygardens#index'
		get '/mygardens/new', to: 'mygardens#new'
		post '/mygardens', to: 'mygardens#create'
		get '/mygardens/:id', to: 'mygardens/plants#index'
    delete '/mygardens/:garden_id/plants/:plant_id', to: 'mygardens/plants#destroy'
		post '/plants', to: 'plants#create'
		get '/plants/:id/mygardens', to: 'mygardens#show', as: 'plants_mygardens'

		delete '/mygardens/:id', to: 'mygardens#destroy'

		namespace :mygardens do
			post '/:garden_id/plants/:plant_id', to: 'plants#create', as: 'plants'
		end
	end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    result = PlantService.get_multiple_info(params['search'])
    plants = result.map { |plant| ApiPlant.new(plant) }
    render locals: {plants: plants}
  end

  def show
    result = PlantService.get_individual_plant_details(params['format'])
    return @error = "Bad Plant" if result == "Bad Plant"
    render locals: {plant: ApiPlant.new(result)}
  end
end

app/views/search/index.html.erb
<center>
<section class='plant_info'>
  <div class="container-1">
    <% plants.map do |plant| %>
    <div class="cards">
      <div class="cards__item">
      <div class="card" style="width: 18rem;">
        <div class="image">
          <img class="card-img-top"<%= image_tag(plant.image, height:'200', width: '150') %>
        </div>
        <div class="card-body">
          <div class="name">
            <h2><%= link_to plant.name.capitalize, search_details_path(plant.name)%></h2>
          </div>
          <% if !plant.description.nil? %>
          <div class="description">
            <p class="card-text"><%= plant.description[0..150] + "..." %></p>
          </div>
          <% else %>
          <p>No description currently available</p>
          <% end %>
        </div>
      </div>
    </div>
    </div>
    <% end %>
  </div>
</section>
</center>

app/views/search/show.html.erb
<center>
  <% if @error %>
    <h2>We are sorry, no details currently avaiable for this plant. Check back soon. </h2>
  <% else %>
    <div class="container-1">
      <div class="plant-cards">
        <div class="cards__item">
          <div class="card-1">
            <br><br><img class="card-img-top"<%= image_tag(plant.image, height:'400', width: '300') %>
            <div class="card-body">
              <% if current_user.nil? %>
                <%= link_to 'Login With Google to Add to your Garden!', '/login' %>
              <% else %>
              	<%= form_tag user_plants_path() do %>
              		<%= hidden_field_tag :name, plant.name %>
              		<%= hidden_field_tag :image, plant.image %>
              		<%= hidden_field_tag :perennial, plant.perennial %>
              		<%= hidden_field_tag :first_harvest, plant.first_harvest %>
              		<%= hidden_field_tag :last_harvest, plant.last_harvest %>
              		<%= hidden_field_tag :description, plant.description %>
              		<%= hidden_field_tag :sun, plant.sun %>
              		<%= hidden_field_tag :height, plant.height %>
              		<%= hidden_field_tag :spread, plant.spread %>
              		<%= hidden_field_tag :spacing, plant.spacing %>
              		<%= submit_tag 'Add to MyGarden' %>
              	<% end %>
              <% end %>
            </div>
          </div>
          <div class="cards__item">
          <div class="card-2 bg-light mb-3">
            <div class="card-body plant_details">
              <h2>Name: <%=  plant.name.capitalize %> </h2>
              <p>Perennial: <%=  plant.perennial %> </p>
              <p>Time to First Harvest: <%=  plant.first_harvest %></p>
              <p>Time to Last Harvest: <%=  plant.last_harvest %></p>
              <p>Description: <%=  plant.description %></p>
              <p>Amount of Sun: <%=  plant.sun %></p>
              <p>Average Height: <%=  plant.height %> cm </p>
              <p>Average Spread: <%=  plant.spread %> cm </p>
              <p>How to Sow: <%=  plant.sowing %> </p>
              <p>Average Spacing <%=  plant.spacing %> </p>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</center>