config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  root 'welcome#index'
  get '/about', to: 'about#show'

  get '/login', to: 'visitors/sessions#new'

  get '/search', to: 'search#index'
  get '/search/details', to: 'search#show'

  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#googleAuth'
  get '/auth/failure', to: redirect('/')

  get '/profile/questionaire', to: 'profiles#new'
  get '/profile/:id', to: 'profiles#show'
  get '/profile/:id/edit', to: 'profiles#edit'
  patch '/profile/:id', to: 'profiles#update'
  post '/profile', to: 'profiles#create'
  delete '/profile/:id', to: 'profiles#destroy'

  get '/plants', to: 'plants#index'

	namespace :user do
		get '/mygardens', to: 'mygardens#index'
		get '/mygardens/new', to: 'mygardens#new'
		post '/mygardens', to: 'mygardens#create'
		get '/mygardens/:id', to: 'mygardens/plants#index'
    delete '/mygardens/:garden_id/plants/:plant_id', to: 'mygardens/plants#destroy'
		post '/plants', to: 'plants#create'
		get '/plants/:id/mygardens', to: 'mygardens#show', as: 'plants_mygardens'

		delete '/mygardens/:id', to: 'mygardens#destroy'

		namespace :mygardens do
			post '/:garden_id/plants/:plant_id', to: 'plants#create', as: 'plants'
		end
	end
end

app/views/partials/_nav.html.erb
<nav class="navbar navbar-expand-lg fixed-top"" style="background-color: #8FBC8F;">
  <%= form_with(url: "/search", method: "get", local: true) do %>
    <%= text_field_tag 'search', nil, placeholder: 'Search plants...' %>
    <%= submit_tag "Search", class: "btn btn-primary my-2 my-sm-0" %>
  <% end %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" <%=link_to "Home", '/'%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "About", about_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Browse All Plants", '/plants' %></a>
      </li>
      <% if current_user %>
        <li class="nav-item">
          <a class="nav-link" <%= link_to 'My Garden', '/user/mygardens'%></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to 'My Profile', "/profile/#{current_user.id}" %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to 'Sign Out', '/logout', method: :delete %></a>
        </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link" <%=link_to 'Sign In', '/login', class: "px2"%></a>
        </li>
      <% end %>
    </ul>
  </div>
</nav>