config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  root 'welcome#index'
  get '/about', to: 'about#show'

  get '/login', to: 'visitors/sessions#new'

  get '/search', to: 'search#index'
  get '/search/details', to: 'search#show'

  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#googleAuth'
  get '/auth/failure', to: redirect('/')

  get '/profile/questionaire', to: 'profiles#new'
  get '/profile/:id', to: 'profiles#show'
  get '/profile/:id/edit', to: 'profiles#edit'
  patch '/profile/:id', to: 'profiles#update'
  post '/profile', to: 'profiles#create'
  delete '/profile/:id', to: 'profiles#destroy'

  get '/plants', to: 'plants#index'

	namespace :user do
		get '/mygardens', to: 'mygardens#index'
		get '/mygardens/new', to: 'mygardens#new'
		post '/mygardens', to: 'mygardens#create'
		get '/mygardens/:id', to: 'mygardens/plants#index'
    delete '/mygardens/:garden_id/plants/:plant_id', to: 'mygardens/plants#destroy'
		post '/plants', to: 'plants#create'
		get '/plants/:id/mygardens', to: 'mygardens#show', as: 'plants_mygardens'

		delete '/mygardens/:id', to: 'mygardens#destroy'

		namespace :mygardens do
			post '/:garden_id/plants/:plant_id', to: 'plants#create', as: 'plants'
		end
	end
end

app/models/plant.rb
class Plant < ApplicationRecord
  has_many :garden_plants
  has_many :gardens, through: :garden_plants
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def index
    json = PlantService.get_all_plants
    plants = json.map { |plant| ApiPlant.new(plant) }
    render locals: {plants: plants.paginate(:page => params[:page], :per_page => 24)}
  end
end

app/controllers/user/mygardens/plants_controller.rb
class User::Mygardens::PlantsController < User::BaseController
  def index
    render locals: { garden: Garden.find(params[:id]) }
  end

  def create
    result = update_garden
    flash[:notice] = "We're updating your calendar with the harvest time of your #{result[:plant].name.downcase}"
    redirect_to user_path(result[:garden].id)
  end

  def destroy
    remove_garden
    redirect_to user_path(params[:garden_id])
  end

  private 

  def update_garden
    garden = Garden.find(params[:garden_id])
    plant = Plant.find(params[:plant_id])
    garden.plants << plant
    garden.save
    NotificationSenderJob.perform_later(garden, plant)
    { garden: garden, plant: plant }
  end

  def remove_garden
    garden_plant = GardenPlant.where("garden_id= #{params[:garden_id]} AND plant_id= #{params[:plant_id]}").first
    events = garden_plant.events.to_a
    NotificationRemoverJob.perform_later(events, current_user)
    garden_plant.destroy
  end

end

app/controllers/user/mygardens_controller.rb
class User::MygardensController < User::BaseController 
	def index
		render locals: {gardens: User.find(current_user.id).gardens}
	end

	def new
	end

	def show
		@plant = Plant.find(params[:id])
	end

	def create
    garden = current_user.gardens.create(garden_params)
    return redirect_to user_mygardens_path if garden.save
		
		flash[:notice] = "Your new garden needs a name"
		redirect_back(fallback_location: root_path)
	end

	def destroy
		Garden.find(params[:id]).destroy
		redirect_to user_mygardens_path
	end

	private

	def garden_params
		params.permit(:name, :address, :city, :state, :zip)
  end
  
end

app/controllers/user/plants_controller.rb
class User::PlantsController < User::BaseController
	def create
		plant = Plant.where(name: params[:name]).first
		if !plant
			plant = Plant.create(plant_params)
		end
		redirect_to user_plants_mygardens_path(plant.id)
	end

	private

	def plant_params
		params.permit(
			:name,
			:image,
			:perennial,
			:first_harvest,
			:last_harvest,
			:description,
			:sun,
			:height,
			:spread,
			:sowing,
			:spacing
		)
	end
end

app/views/user/mygardens/plants/index.html.erb
<center>
	<div class="jumbotron jumbotron-fluid">
	<h2><%= garden.name %></h2>
<% if garden.plants.empty? %>
	<h3> No plants in this garden. Find something you would like to grow and add them to keep track of what you have planted </h3>
<% else %>
<div class="container-1">
	<% garden.plants.each do |plant| %>
	<div class="cards">
		<div class="cards__item">
		<div class="card" style="width: 18rem;">
			<img class="card-img-top"<%= image_tag(plant.image, height:'200', width: '150') %>
			<div class="card-body">
				<div class="name">
					<h2><%= link_to plant.name.capitalize, search_details_path(plant.name)%></h2>
				</div>
				<% if !plant.description.nil? %>
				<div class="description">
					<p class="card-text"><%= plant.description[0..150] + "..." %></p>
				</div>
				<% else %>
				<p>No description currently available</p>
				<% end %>
				<div class="delete-plant-<%=plant.id%>"><%= link_to "Delete From Garden", user_mygardens_plants_path(garden.id, plant.id), method: :delete, data: {confirm: "Are you sure?"} %></div>
			</div>
		</div>
	</div>
	</div>
	<% end %>
</div>
<% end %>
</div>
</center>